-- MySQL Script generated by MySQL Workbench
-- 2015年08月27日 星期四 13时54分38秒
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estate
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estate` ;
CREATE SCHEMA IF NOT EXISTS `estate` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `estate` ;

-- -----------------------------------------------------
-- Table `estate`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`group` ;

CREATE TABLE IF NOT EXISTS `estate`.`group` (
  `groupID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `groupName` VARCHAR(25) NULL COMMENT '组名',
  `auth` TEXT NULL COMMENT '权限',
  PRIMARY KEY (`groupID`))
COMMENT = '用户组';


-- -----------------------------------------------------
-- Table `estate`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`admin` ;

CREATE TABLE IF NOT EXISTS `estate`.`admin` (
  `adminID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45) NULL COMMENT '盐',
  `email` VARCHAR(45) NULL,
  `groupID` INT UNSIGNED NULL COMMENT '所属用户组',
  `lastLogin` VARCHAR(15) NULL,
  PRIMARY KEY (`adminID`),
  INDEX `FK_ADMIN_GROUP_idx` (`groupID` ASC),
  CONSTRAINT `FK_ADMIN_GROUP`
    FOREIGN KEY (`groupID`)
    REFERENCES `estate`.`group` (`groupID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
COMMENT = '网站后台登陆用户';


-- -----------------------------------------------------
-- Table `estate`.`garden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`garden` ;

CREATE TABLE IF NOT EXISTS `estate`.`garden` (
  `gardenID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gardenCode` VARCHAR(25) NULL COMMENT '园区编号',
  `gardenName` VARCHAR(25) NULL COMMENT '园区名字',
  PRIMARY KEY (`gardenID`))
COMMENT = '园区';


-- -----------------------------------------------------
-- Table `estate`.`building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`building` ;

CREATE TABLE IF NOT EXISTS `estate`.`building` (
  `buildingID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `buildingCode` VARCHAR(25) NULL COMMENT '楼栋编号',
  `buildingName` VARCHAR(25) NULL COMMENT '楼栋名',
  `gardenID` INT UNSIGNED NULL,
  PRIMARY KEY (`buildingID`),
  INDEX `FK_BUILDING_GARDEN_idx` (`gardenID` ASC),
  CONSTRAINT `FK_BUILDING_GARDEN`
    FOREIGN KEY (`gardenID`)
    REFERENCES `estate`.`garden` (`gardenID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '楼栋';


-- -----------------------------------------------------
-- Table `estate`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`unit` ;

CREATE TABLE IF NOT EXISTS `estate`.`unit` (
  `unitID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `unitCode` VARCHAR(25) NULL COMMENT '单元编号',
  `unitName` VARCHAR(25) NULL COMMENT '单元名称',
  `buildingID` INT UNSIGNED NULL,
  PRIMARY KEY (`unitID`),
  INDEX `FK_UNIT_BUILDING_idx` (`buildingID` ASC),
  CONSTRAINT `FK_UNIT_BUILDING`
    FOREIGN KEY (`buildingID`)
    REFERENCES `estate`.`building` (`buildingID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
COMMENT = '单元表';


-- -----------------------------------------------------
-- Table `estate`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`user` ;

CREATE TABLE IF NOT EXISTS `estate`.`user` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(15) NOT NULL COMMENT '用户电话',
  `password` VARCHAR(32) NOT NULL,
  `salt` VARCHAR(45) NULL COMMENT '盐',
  `username` VARCHAR(20) NULL COMMENT '用户名',
  `userCode` VARCHAR(30) NULL COMMENT '业主编号',
  `carNum` VARCHAR(45) NULL COMMENT '车牌号',
  `IDcard` VARCHAR(20) NULL COMMENT '身份证号',
  `unitID` INT UNSIGNED NULL COMMENT '单元外键',
  `doorPart` VARCHAR(20) NULL COMMENT '门牌号',
  `joinTime` VARCHAR(15) NULL COMMENT '入住时间',
  `createTime` VARCHAR(15) NULL COMMENT '添加时间',
  PRIMARY KEY (`userID`),
  INDEX `FK_USER_UNIT_idx` (`unitID` ASC),
  CONSTRAINT `FK_USER_UNIT`
    FOREIGN KEY (`unitID`)
    REFERENCES `estate`.`unit` (`unitID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'app登陆用户';


-- -----------------------------------------------------
-- Table `estate`.`notice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`notice` ;

CREATE TABLE IF NOT EXISTS `estate`.`notice` (
  `niticeID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NULL COMMENT '公告标题',
  `description` VARCHAR(255) NULL COMMENT '公告描述',
  `detail` TEXT NULL COMMENT '公告详情',
  `createTime` VARCHAR(15) NULL,
  `expireTime` VARCHAR(15) NULL COMMENT '公告过期时间',
  `picPath` VARCHAR(255) NULL COMMENT '公告图片路径',
  `creater` VARCHAR(25) NULL COMMENT '公告创建人',
  PRIMARY KEY (`niticeID`))
ENGINE = InnoDB
COMMENT = '公告表';


-- -----------------------------------------------------
-- Table `estate`.`complain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`complain` ;

CREATE TABLE IF NOT EXISTS `estate`.`complain` (
  `complainID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NULL COMMENT '投诉标题',
  `detail` TEXT NULL COMMENT '投诉描述',
  `picPath` VARCHAR(255) NULL COMMENT '投诉图片路径',
  `createTime` VARCHAR(15) NULL COMMENT '投诉时间',
  `status` INT NULL DEFAULT 0 COMMENT '投诉状态',
  `score` INT NULL COMMENT '用户打分',
  `adminID` INT UNSIGNED NULL COMMENT '处理人',
  `userID` INT UNSIGNED NULL COMMENT '用户',
  PRIMARY KEY (`complainID`),
  INDEX `FK_COMPLAIN_USER_idx` (`userID` ASC),
  INDEX `FK_COMPLAIN_ADMIN_idx` (`adminID` ASC),
  CONSTRAINT `FK_COMPLAIN_USER`
    FOREIGN KEY (`userID`)
    REFERENCES `estate`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COMPLAIN_ADMIN`
    FOREIGN KEY (`adminID`)
    REFERENCES `estate`.`admin` (`adminID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
COMMENT = '用户投诉表';


-- -----------------------------------------------------
-- Table `estate`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`service` ;

CREATE TABLE IF NOT EXISTS `estate`.`service` (
  `serviceID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(25) NULL DEFAULT '人工服务',
  `feeInfo` VARCHAR(32) NULL COMMENT '收费标准',
  `title` VARCHAR(25) NULL COMMENT '服务名称',
  `detail` TEXT NULL COMMENT '服务描述',
  PRIMARY KEY (`serviceID`))
COMMENT = '服务项目表';


-- -----------------------------------------------------
-- Table `estate`.`user_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estate`.`user_service` ;

CREATE TABLE IF NOT EXISTS `estate`.`user_service` (
  `usID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userID` INT UNSIGNED NULL,
  `serviceID` INT UNSIGNED NULL,
  `create_time` VARCHAR(15) NULL COMMENT '申请时间',
  `payStatus` INT NULL DEFAULT 0 COMMENT '支付状态',
  `serviceStatus` INT NULL DEFAULT 0 COMMENT '服务状态',
  `comment` VARCHAR(100) NULL COMMENT '评论',
  PRIMARY KEY (`usID`),
  INDEX `FK_US_SERVICE_idx` (`serviceID` ASC),
  INDEX `FK_US_USER_idx` (`userID` ASC),
  CONSTRAINT `FK_US_SERVICE`
    FOREIGN KEY (`serviceID`)
    REFERENCES `estate`.`service` (`serviceID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_US_USER`
    FOREIGN KEY (`userID`)
    REFERENCES `estate`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
COMMENT = '用户服务表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
